### ISSUE TITLE
add C3L, a luxembourg hackerspace

### ISSUE THREAD

**Issue by Psycojoker** [Psycojoker/hackeragenda#113]
https://level2.lu/

**Comment by Rafiot** [comment]
https://github.com/Psycojoker/hackeragenda/blob/master/agendas/be.py#L1065 :)

**Comment by Psycojoker** [comment]
Syn2cat and level2 are the same thing? I though it was a new hackerspace.

**Comment by Rafiot** [comment]
No, it is the same thing, syn2cat is the ASBL managing level2 (the local).

But there is a new place of the C3L: https://wiki.c3l.lu/doku.php - https://wiki.c3l.lu/doku.php?id=events:index#ical

**Comment by Psycojoker** [comment]
Oh cool, thx for the info :)
