### ISSUE TITLE
Intel IoT Roadshow in Amsterdam

### ISSUE THREAD

**Issue by Lisastamm** [Psycojoker/hackeragenda#116]
Ola Psyco! Checked the agenda and this one http://iotroadshow.intel.com is not in there! As you said, SKANDALOOSE! 

During the weekend of 23-24 April you can build projects with the Intel® Edison ™ Dev Kit, given away by Intel to the first 100 registered onsite to the hackathon! The Dev Kit includes sensors, software and accessories. The hackathon is free, and top 3 wins moneeeey! Pretty sweet indeed :) 

Hope it is awesome enough to put on there, cheers!

**Comment by titouanc** [comment]
Please note that the events could not be added by hand (but you could implement the hackeragenda API on your site, more on this on https://github.com/Psycojoker/hackeragenda#implement-the-hackeragenda-api).

Also the event does not take place in belgium.
