### ISSUE TITLE
Use real logging in fetch_events

### ISSUE THREAD

**Issue by C4ptainCrunch** [Psycojoker/hackeragenda#22]
For now, logging is a bit anarchic. It would be nice to use a logging lib ([Logbook](http://pythonhosted.org/Logbook/) maybe ?) to be able to output logs at different verbosity levels. Also provide a helper so that all parsers make identical logs.

If it's ok for you i'm willing to do it.

**Comment by Psycojoker** [comment]
I'm cleaning up stuff, this one hasn't move and it's a nice to have, either someone will submit a patch, either it will be forgotten.
